### ISSUE TITLE
in control/job.py Harvester setting assumes multiple jobs per pilot

### ISSUE THREAD

**Issue by dougbenjamin** [PanDAWMS/pilot2#152]
This lines - 
https://github.com/PanDAWMS/pilot2/blob/2bd9eaba244eca4701dc35948dfecee6bc7bc1fa/pilot/control/job.py#L872-L876

in control/job.py Harvester setting assumes multiple jobs per pilot

need to differential many to one running of the harvester from one to one running. 
(many jobs per pilot)  vs 1 job per pilot.

**Comment by PalNilsson** [comment]
The default in request_new_jobs() is njob=1, it's not ever used with more jobs; @DanilaOleynik can you have a look at this? We have discussed downloading bulk jobs before but as I remember it, there was no support for it on the other end.
