### ISSUE TITLE
Why does is_harvester_mode require -  "and not args.update_server"

### ISSUE THREAD

**Issue by dougbenjamin** [PanDAWMS/pilot2#153]
Why does is_harvester_mode require -  "and not args.update_server"

Please the lines referenced bellow:

https://github.com/PanDAWMS/pilot2/blob/a78652f0d6866d0829e8d0d5bff20af85cecbc8a/pilot/util/harvester.py#L30-L36

**Comment by DanilaOleynik** [comment]
Hi Doug, 
I think it's required for avoiding direct communication between Pilot and PanDA server, and use only communication through Harvester. It's needed if worker nodes have no external network communication.
