### ISSUE TITLE
Correct propagation of protocols into traces.

### ISSUE THREAD

**Issue by TomasJavurek** [PanDAWMS/pilot2#154]
1) This is not protocol, but copytool:
https://github.com/PanDAWMS/pilot2/blob/next/pilot/api/data.py#L346
so the field should be named properly in the trace.
`module = self.copytool_modules[name]['module_name']
  self.logger.info('trying to use copytool=%s for activity=%s' % (name, activity))
  copytool = __import__('pilot.copytool.%s' % module, globals(), locals(), [module], -1)
  self.trace_report.update(protocol=name)`

2) The protocol should be filled in a separate field. For that we would need to populate the protocol list and the protocol_id into fspec. While the protocol_id is never populated, and the list of protocols is created only for stage_out. Not clear to me, where to do that. I'll apply a dirty solution: extract protocol from surl directly in copytoole module and populate the trace there.

3) This is dirty:
https://github.com/PanDAWMS/pilot2/blob/next/pilot/api/data.py#L426
`            if replica:
                surl = self.get_preferred_replica(replicas, ['srm']) or replicas[0]  # prefer SRM protocol for surl -- to be verified
                self.logger.info("[stage-in] surl (srm replica) from Rucio: pfn=%s, ddmendpoint=%s" % (surl, ddmendpoint))
break`
shouldn't there be _if not replica_ ?

**Comment by PalNilsson** [comment]
1-2 were later fixed. The protocol=copytool line above remains currently however, just as a kind of default value, but gets set properly later. Maybe best to simply remove the line mentioned, ie not put a default value since it is anyway not a correct value and useless. 3 is now irrelevant since the code was changed long ago.
