### ISSUE TITLE
[Question] AGIS PQ fields: container_type setup

### ISSUE THREAD

**Issue by a6350202** [PanDAWMS/pilot2#212]
Hello,

Now our site run T1 jobs in kubernetes container, we want to switch to pilot2 and disable singularity in this queue.  
What does the setup of container_type="docker:wrapper" on AGIS mean?   
"pilot will launch a container and run inside"   or   " pilot was already in container and then run"?  
Or other setup I should do?  
  
Thanks!

**Comment by PalNilsson** [comment]
Hi Ming,
"docker:wrapper" means that the wrapper will be in charge of starting the pilot inside a docker container (not sure if that is fully supported or relevant for you - this is not a pilot setup question). "singularity:pilot" means the the pilot will execute the payload inside a singularity container. Please discuss any queue changes with the DPA team.
Cheers, Paul

**Comment by a6350202** [comment]
OK, Thank you @PalNilsson
