### ISSUE TITLE
Buggy calculation of used cores

### ISSUE THREAD

**Issue by davidgcameron** [PanDAWMS/pilot2#215]
On a single core job I see in the log

```
2019-10-03 10:15:55,351 | DEBUG    | job_monitor         | pilot.util.monitoring            | check_number_used_cores   | ps axo pgid,psr | sort | grep 600 | uniq | wc -l:
6
2019-10-03 10:15:55,351 | DEBUG    | job_monitor         | pilot.util.monitoring            | check_number_used_cores   | set number of actual cores to: 6

```
grepping for the process id is unreliable because it matches any id with those numbers inside, eg 6001, 26004

Maybe [psutil](https://pypi.org/project/psutil/) is a better alternative?

**Comment by davidgcameron** [comment]
I don't have any personal experience of using psutil unfortunately, I just know it's widely used for monitoring system processes.

**Comment by agbogdan** [comment]
ps can match the pid itself (the option -q), for this case "ps -q 600 axo pgid,psr" could be used probably

**Comment by agbogdan** [comment]
I looked into man ps: there is no pgid in select options. Other selections (by pid sid ppid etc) may not work as desired.
Another solution is to use grep with regex: 
grep -E '^600\s'

**Comment by PalNilsson** [comment]
David, sorry about forgetting this one and thanks for reminding me - I believe it can be fixed by adding the -x option to the grep command, which should only return the exact matches. I tried for a long time to get AleDS to make psutil available via cvmfs but it never materialised. Anyway, -x seems simple enough. Added to the dev pilot.

**Comment by PalNilsson** [comment]
For reference; this seems to work:
cmd = "ps axo pgid,psr | sort | grep %d | uniq | awk '{print $1}' | grep -x %d | wc -l" % (job.pgrp, job.pgrp)
Horrible.. I would prefer using some python module but it seems there is nothing useful.
