### ISSUE TITLE
Final heartbeat not sent after stage in failure

### ISSUE THREAD

**Issue by davidgcameron** [PanDAWMS/pilot2#220]
https://bigpanda.cern.ch/job?pandaid=4512622976

This job failed due to a rucio problem but did not send the final heartbeat, so ended up as taskbuffer:300 error (lost heartbeat).

The full log is attached here

[4512622976.out.txt](https://github.com/PanDAWMS/pilot2/files/3729160/4512622976.out.txt)

**Comment by PalNilsson** [comment]
Fixed in dev pilot v 2.2.1 (2)
