### ISSUE TITLE
Copytools should not overwrite existing output files

### ISSUE THREAD

**Issue by davidgcameron** [PanDAWMS/pilot2#239]
We had a case recently where a job ran twice, and the second job overwrote the output file created by the first job. This led to a different checksum of the file in rucio and storage, causing file transfer and job failures. The pilot should instead fail when it encounters a file which already exists. It seems like rucio mover correctly fails but gfal does not. The fix might be as simple as removing the `-f` here:

https://github.com/PanDAWMS/pilot2/blob/master/pilot/copytool/gfal.py#L140

but other copytools should be checked too.

**Comment by PalNilsson** [comment]
Thanks David. Alexey can you please check this?
