### ISSUE TITLE
Improve killing orphans regexp

### ISSUE THREAD

**Issue by fbarreir** [PanDAWMS/pilot2#247]
In kubernetes we run a python script to setup the environment and run the pilot wrapper. Once the pilot has executed a job, it invokes the kill orphan method and kills anything running under the same user, including the startup script. So the startup script can't finish properly and upload the logs.

 I'm trying to fall into one of the exceptions, like renaming my python script to "pilots_starter.py" (see https://github.com/PanDAWMS/pilot2/blob/master/pilot/util/processes.py#L346). However I don't think the regexp matches properly the command, since the command can contain whitespaces but the regexp cuts after the first whitespace. 

Currently it works like this. See that from "python pilots_starter.py" only "python" is kept:
```
[root@ae86f0c2304b /]# ps -o pid,ppid,args
  PID  PPID COMMAND
...
   33     1 python pilots_starter.py
[root@ae86f0c2304b /]# python
Python 2.7.5 (default, Apr  9 2019, 14:30:50)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> pattern = re.compile('(\d+)\s+(\d+)\s+(\S+)')
>>> line = '33     1 python pilots_starter.py'
>>> ids = pattern.search(line)
>>> print(ids.group(3))
python
```
Proposal to change the pattern to accept whitespaces for the last block:

```
>>> pattern = re.compile('(\d+)\s+(\d+)\s+([\S\s]+)')
>>> ids = pattern.search(line)
>>> print(ids.group(3))
python pilots_starter.py
```

**Comment by rptaylor** [comment]
Aha, this must be the source of all the errors I have been seeing on the cluster. All I see is 
```
/usr/bin/bash: line 1:     7 Killed                  python k8s_startup_script.py
```

since all other output is captured by the script getting killed. Moreover the script getting killed is responsible for uploading the log files, but unable to do so when it gets killed. 
This happens to over 60% of jobs. The pilot and Panda job are (presumably) completing successfully though. But we have no visibility of job outcome and this makes it hard to find any other problems that may be occurring.

**Comment by PalNilsson** [comment]
Hi ok, updated in the latest dev pilot. Thanks (will close this issue once the new pilot has been released, no date yet though)

**Comment by PalNilsson** [comment]
Hi again, it seems the pattern change causes problems.. Maybe we need an 'if kubernetes'-line? See e.g. job
https://bigpanda.cern.ch/job?pandaid=4599865064
error + cut off stdout.

**Comment by fbarreir** [comment]
Hi Paul,
I don't see any stdout for that example, but it's true that the pilot might be killing the wrapper now, because this condition is no longer true:
https://github.com/PanDAWMS/pilot2/blob/master/pilot/util/processes.py#L351
`
                if args.endswith('bash'):
                    logger.info("will not kill bash process")
`
It would also have to be adapted to something like
`
                if 'bash' in args: # or if 'runpilot2-wrapper.sh' in args:
                    logger.info("will not kill bash process")
`
The thing is that I don't think this part works as intended, since args is only the first word of the command. So it's difficult to implement any new 'if kubernetes' condition.
Cheers,
Fernando

**Comment by fbarreir** [comment]
* I see what you mean with the kubernetes option. We can try to use the PILOT_NOKILL env variable in the shortterm
https://github.com/PanDAWMS/pilot2/blob/master/pilot/util/processes.py#L327
In the longterm I prefer if there is a better fix, since otherwise there is no zombie cleanup at all and we need to remember a new variable in the templates.

**Comment by PalNilsson** [comment]
Ok, the stdout disappeared in the meantime. The 'if bash'-change works fine:
https://aipanda024.cern.ch/condor_logs_2/20-01-07_13/grid.16975124.0.out
/Paul

**Comment by rptaylor** [comment]
Hi,

So what is the status of this, has it been fixed by https://github.com/PanDAWMS/pilot2/commit/addea4bb708085e9d8d3187e33512e5476fea231#diff-a27694ffcf4e8da1086ef60b00dba60b34c834dfea749fd8599a63fd2fe98484  and can be closed  ?

IIUC the pattern matching for "pilots_starter.py"  now works properly, so the script avoids being killed via that exception?

Thanks!

**Comment by PalNilsson** [comment]
Hi,
Yes as far as I know this has been fixed. Closing.
/Paul
