### ISSUE TITLE
Exception when running multiple jobs per pilot

### ISSUE THREAD

**Issue by nikmagini** [PanDAWMS/pilot2#258]
Pilot version 2.4.2 running with timefloor=60

If the first job finishes before timefloor, pilot fetches a second job from PanDA; however, the pilot gets an exception and exits gracefully, and the second job never runs and eventually fails with jobDispatcher error 102

Example:

https://bigpanda.cern.ch/harvesterworkerinfo/?harvesterid=CERN_central_B&workerid=134818652
https://aipanda183.cern.ch/condor_logs_2/20-02-27_23/grid.5231873.3.out

exception caught by thread run() function: (<type 'exceptions.IndexError'>, IndexError('deque index out of range',), <traceback object at 0x2b9dcc353b90>)
Traceback (most recent call last):
  File "/pool/condor/dir_2357/tmp/atlas_6G0RwFAb/pilot2/pilot/common/exception.py", line 434, in run
    self._Thread__target(**self._Thread__kwargs)
  File "/pool/condor/dir_2357/tmp/atlas_6G0RwFAb/pilot2/pilot/control/job.py", line 1921, in job_monitor
    update_time = send_heartbeat_if_time(jobs[i], args, update_time)
IndexError: deque index out of range

None
exception has been put in bucket queue belonging to thread 'job_monitor'
setting graceful stop in 10 s since there is no point in continuing

More examples:
https://bigpanda.cern.ch/jobs/?computingsite=CERN&hours=48&jobstatus=failed&jobdispatchererrorcode=102&display_limit=100

**Comment by PalNilsson** [comment]
Fixed long ago.
