### ISSUE TITLE
Stage In/Out is a parts of workflow, but not a job execution. 

### ISSUE THREAD

**Issue by DanilaOleynik** [PanDAWMS/pilot2#33]
Setup of stage in/out mostly relate with workflow and should not be implemented as method of Job class.     
https://github.com/PanDAWMS/pilot2/blob/4977788ab717517f760f6713789d3c480ecc82b8/job.py#L410

**Comment by PalNilsson** [comment]
(note that this refers to the minipilot branch and not pilot2; Daniel may comment himself since it's all his code)

**Comment by complynx** [comment]
Yep, minipilot wasn't meant to have the same classes or anything. It was to be simple. And this was one of the solutions.
