### ISSUE TITLE
Pilot may kill unrelated processes in kill_orphans / kill its parent / cause resources not to be freed

### ISSUE THREAD

**Issue by olifre** [PanDAWMS/pilot2#346]
The current pilot code in `kill_orphans` collects any process with `PPID=1` belonging to the pilot user and sends `kill -9` (with a few hardcoded exceptions). 

Apart from the recent problem at RAL (killing `runpilot2-wrapper.sh`) which is now blacklisted, there are several more issues:
1. Completely unrelated processes on the same node can be killed. 
2. The pilot can still perform parenticide, i.e. kill it's own parent, thus killing itself. 
3. Sending `kill -9` directly without a `SIGTERM` first may for some processes cause resources not to be freed, errors not to be logged etc. 

We are now encountering this issue again in another incantation (running containers with PID namespace and a `condor_master` as first process inside, which itself has the Pilot in the process tree, then the pilot kills `condor_master` as an "orphan", killing its parent and thus going to the orphanage itself). 

I have several ideas for improvements to the logic, but all require quite some development work (for which I currently don't have the resources to contribute myself). 
In increasing order of complexity and robustness (sadly, these are proportional), my ideas are:

1. Send a regular `SIGTERM` first, and a `SIGKILL` only after a grace period.
This should allow killed processes to clean up (e.g. lock files, FUSE mounts etc. which may be left dangling otherwise) and allow them to log the death. 
2. Collect all `PID`s following the chain from the pilot `PID` itself via its `PPID` up to `PID=1`, and put all these processes on a whitelist of processes which will not be killed, to prevent prevent parenticide. 
3. Let the pilot open up a PID namespace in a user namespace (if the site has these enabled) and have a dedicated `PID=1` process (similar e.g. to [tini](https://github.com/krallin/tini) or Singularity's `sinit`). Once the `PID=1` process in the namespace dies, the kernel will clean up things automagically.

**Comment by maxfischer2781** [comment]
My hunch seeing this issue was that process groups should allow to separate "current pilot processes" from the rest. Search shows the pilot does use ``setpgrp`` already at least in some parts.

Any idea why that isn't enough?

**Comment by olifre** [comment]
> Any idea why that isn't enough?

I think the problem is that the process tree ends up like this (full example from our setup):
```
$ ps -eo pid,ppid,pgid,sid,command
  PID  PPID  PGID   SID COMMAND
    1     0     0     0 sinit
   13     1    13    13 /usr/sbin/condor_master -f
   71    13    13    13 condor_procd -A /jwd/condor/lock/procd_pipe -L /jwd/condor/log/uni-bonn-1452f9c284/ProcLog -R 1000000 -S 60 -C 509
   72    13    72    72 condor_shared_port -f
   75    13    75    75 condor_startd -f
  152    75   152   152 condor_starter -f cloud-htcondor-ce-1-kit.gridka.de
  158   152   158   158 /bin/bash /jwd/condor/execute/dir_152/condor_exec.exe -s DE-TARDIS -r DE-TARDIS -q DE-TARDIS -j managed -i PR -w generic --pilot-user ATLAS --url https://pandaserver.cern.ch -d --harvester-submit-mode PULL --allow-
 4095   158  4095   158 /usr/bin/python2 pilot2/pilot.py -q DE-TARDIS -i PR -j managed --pilot-user=ATLAS -w generic --pilot-user ATLAS --url https://pandaserver.cern.ch -d --harvester-submit-mode PULL --allow-same-user=False --job-type=m
 8895  4095  8895   158 /bin/bash -c export X509_USER_PROXY=/jwd/condor/execute/dir_152/x509up_u25606_prod;if [ -z "$ATLAS_LOCAL_ROOT_BASE" ]; then export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase; fi;export thePl
 8923  4095  8923   158 /bin/bash -c cd /jwd/condor/execute/dir_152/tmp/atlas_wvXmswxN/PanDA_Pilot-5041405634;export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase;source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.s
 9021  8895  8895   158 /bin/bash /tmp/home/atlasprd/.alrb/container/scripts/startContainer.sh.G4DdxB -c x86_64-centos7-gcc62-opt -s /srv/my_release_setup.sh -r /srv/container_script.sh -e -C
 9461  9021  8895   158 Singularity runtime parent
 9508  9461  8895   158 sinit
 9546  9508  8895   158 /bin/bash /alrb/.bashrc
12818  8923  8923   158 prmon --pid 8895 --filename memory_monitor_output.txt --json-summary memory_monitor_summary.json --interval 60
13403  9546  8895   158 /bin/bash /alrb/.bashrc
13404 13403  8895   158 python /cvmfs/atlas.cern.ch/repo/sw/software/21.6/AthGeneration/21.6.63/InstallArea/x86_64-centos7-gcc62-opt/share/Gen_tf.py --maxEvents=2000 --skipEvents=17478000 --ecmEnergy=13000 --firstEvent=337478001 --jobConf
13407 13404  8895   158 /bin/sh ./runwrapper.generate.sh
13408 13404  8895   158 MemoryMonitor --pid 2345 --filename mem.full.generate --json-summary mem.summary.generate.json --interval 30
13409 13407  8895   158 /cvmfs/atlas.cern.ch/repo/sw/software/21.6/sw/lcg/releases/LCG_88b/Python/2.7.13/x86_64-centos7-gcc62-opt/bin/python -tt /cvmfs/atlas.cern.ch/repo/sw/software/21.6/AthGeneration/21.6.63/InstallArea/x86_64-centos7-g
```
i.e.  there's a second `bash` instance with `prmon` below in a different process group. 

I'm not sure whether this is expected / wanted. Another option would be to use the `sid` which looks fine at least in this example. 

Checking development history, it seems `kill_orphans` was added in 2018:
https://github.com/PanDAWMS/pilot2/commit/1f7ffdfae839b2ae42cef9d5686d54948b82f451
and PGID-based killing in 2019:
https://github.com/PanDAWMS/pilot2/commit/fe45c0fe9b0ad78148b2c76a4ba1ce4f93720ebf
so maybe another ingredient is history?

**Comment by olifre** [comment]
Thanks!
In the meantime, we've already set `PILOT_NOKILL` and Rod has additionally set `timefloor=0` so we should be double-protected from this for the time being.

**Comment by PalNilsson** [comment]
Hi, ideas 1) and 2) above have been added to the dev pilot. I'll try to have it released this week.

**Comment by olifre** [comment]
@PalNilsson Thanks! 

While I can't test as easily, I can surely review the code a bit and look for potential issues which could happen in PID namespaced issues. While that's easier with commits I can look at one by one, of course a tarball also works for pythonic code as long as the diff from other changes is not too overwhelming. 

I went through the changes just now and while it definitely is an improvement, some assumptions in the changes related to this issue feel a bit dangerous to me, if I understand the code correctly, `get_pilot_pid_from_processes` seems to make two assumptions:
1. It assumes the Pilot runs with `pilot.py` and `python` in `args`, and with that determines the Pilot PID, accepting the first found Pilot. Won't that find "any" pilot in the same PID namespace? We may accept multiple ATLAS jobs into one PID namespace at some point, and of course also the common case of running more than one job on a worker node without PID isolation would have more pilots in one PID namespace. 
2. It assumes that processes with a smaller PID are parent processes  / started earlier. This may be very wrong: PIDs are usually limited, some systems default to 32k PIDs, and then wraparound happens. Again, assuming there are multiple pilots running on a machine, or in our case multiple `condor_starter` in a long-lived PID namespace with pilots as childs, wraparound is quite likely. As you see in the example above, we're already at PID numbers above 13000 for a single job in the namespace — 32k is not very far away, so a new `condor_starter` may get a smaller PID than the pilot running there. 

These two points feel a bit dangerous to me, and are not too easily hit with "lab" tests. I think the only safe (but more complex code-wise) way would be to really walk through the process three via the `PPID` and build a "don't kill these" list of PIDs that way, since no assumption on PID ordering can be made.

**Comment by PalNilsson** [comment]
Yes, that's true. I was under the illusion you only have one pilot process in such a namespace. Maybe it's easier if you just suggest an improved kill_orphan() function that will work for you. In any case, unfortunately we're out of time for this pilot version since it seems I need to release it tomorrow. Just make a PR towards the 'next' branch. I will help you test it of course.

**Comment by olifre** [comment]
@PalNilsson I'm sorry it took me so long, but I wanted to wait for a calm time to think about this issue in a more global way. 

The idea I came up with is completely different from the current approach, but should be the most resilient and safest one: What about calling `prctl(PR_SET_CHILD_SUBREAPER, ...)` inside the pilot, and then dropping all the orphan-killing completely? 
`PR_SET_CHILD_SUBREAPER` is supported since kernel 3.4 (i.e. we can rely on it, I think) and causes all detaching processes to be attached to "us" (i.e. the pilot) instead of `PID=1`. 

Going this way (if you agree) would allow to drop all the explicit orphan killing code, and ensure that only processes started below the pilot are killed, even on shared nodes. What do you think about this idea?

**Comment by PalNilsson** [comment]
Hi, sure, we can try it. Should it be called using gdb? Let me know of the exact command.

**Comment by olifre** [comment]
> If `ctypes` can not be used, `gdb` might be the only way. If so, I can surely check out the correct commandline to use.

This works in case we can't rely on `ctypes`, `gdb` API bindings or anything else:
```
import subprocess, os 
subprocess.call(["gdb", "-p", str(os.getpid()), "-batch-silent", "-ex" , "p prctl(36,1,0,0,0)", "-ex", "quit"])
```
But this is much heavier than the `ctypes` call and also would ideally need exception handling.

**Comment by PalNilsson** [comment]
Ok good, thanks. I will test whether ctypes works 'everywhere' (ie where I can reach with RC test jobs). I'll be busy with something else tomorrow but will try it asap, and will let you know.

**Comment by olifre** [comment]
Thanks! There's no immediate urgency, I'm anyways on holidays right now (which helps to think about clean solutions :wink: ) and `PILOT_NOKILL` works quite well for the time being. So for sure take your time in testing. 

In the long run, I hope this also eases maintenance since it allows to drop all the explicit orphan-killing code, and as job isolation with namespaces becomes increasingly popular, it will also remove at least one kind of potential issue. 

PS: I just read in the last pilot release notes that you affiliated me with RAL — I'm actually at the University of Bonn, but indeed we do some things quite similar to what RAL is doing (which explains why we see similar problems).

**Comment by PalNilsson** [comment]
Oh sorry about that, I thought you were with RAL! Enjoy your holidays..

**Comment by PalNilsson** [comment]
For the record; the ctypes python module fails to be imported on at least one site (https://bigpanda.cern.ch/jobs/?prodsourcelabel=rc_test2&jobstatus=failed&piloterrorcode=1365&hours=600&limit=999999&mode=nodrop). The production pilot version will not fail the job in this case (only the dev pilot). The old mechanism will remain in that case. I suggest you continue to use the PILOT_KILL env var (just to prevent the orphan killer from running - you will still have the ctypes mechanism of course).
