### ISSUE TITLE
Wrong message format

### ISSUE THREAD

**Issue by DanilaOleynik** [PanDAWMS/pilot2#58]
https://github.com/PanDAWMS/pilot2/blob/198b0bc13e2ef24166efc8533c5d1cfc4670d578/pilot/user/atlas/common.py#L199

jobMetrics should have format: 'coreCount=%s nEvents=%s dbTime=%s dbData=%s workDirSize=%s' instead of 'core_count=%s n_events=%s db_time=%s db_data=%s'

**Comment by PalNilsson** [comment]
Thanks. I have updated it in my fork. However, should the fields always be included in jobMetrics? In Pilot 1 I only add the fields when they have values (non-null, non-None etc).

**Comment by DanilaOleynik** [comment]
Looks like parser on server side smart enough to use only proper values, but in general i think we need to publish only defined parameters.
